const fluentBorderRadius = {
  "f-none": "0",
  "f-small": "2px",
  "f-medium": "4px",
  "f-large": "6px",
  "f-x-large": "8px",
  "f-circular": "10000px",
};

const fluentFontSize = {
  "f-base100": "10px",
  "f-base200": "12px",
  "f-base300": "14px",
  "f-base400": "16px",
  "f-base500": "20px",
  "f-base600": "24px",
  "f-hero700": "28px",
  "f-hero800": "32px",
  "f-hero900": "40px",
  "f-hero1000": "68px",
};

const fluentLineHight = {
  "f-base100": "14px",
  "f-base200": "16px",
  "f-base300": "20px",
  "f-base400": "22px",
  "f-base500": "28px",
  "f-base600": "32px",
  "f-hero700": "36px",
  "f-hero800": "40px",
  "f-hero900": "52px",
  "f-hero1000": "92px",
};

const fluentFontFamily = {
  "f-base": "'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
  "f-monospace": "Consolas, 'Courier New', Courier, monospace",
  "f-numeric": "Bahnschrift, 'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif",
};

const fluentFontWeight = {
  "f-regular": 400,
  "f-medium": 500,
  "f-semibold": 600,
  "f-bold": 700,
};

const fluentStrokeWidth = {
  "f-thin": "1px",
  "f-thick": "2px",
  "f-thicker": "3px",
  "f-thickest": "4px",
};

const fluentSpacing = {
  "f-horizontal-none": "0",
  "f-horizontal-xxs": "2px",
  "f-horizontal-xs": "4px",
  "f-horizontal-s-nudge": "6px",
  "f-horizontal-s": "8px",
  "f-horizontal-m-nudge": "10px",
  "f-horizontal-m": "12px",
  "f-horizontal-l": "16px",
  "f-horizontal-xl": "20px",
  "f-horizontal-xxl": "24px",
  "f-horizontal-xxxl": "32px",
  "f-vertical-none": "0",
  "f-vertical-xxs": "2px",
  "f-vertical-xs": "4px",
  "f-vertical-s-nudge": "6px",
  "f-vertical-s": "8px",
  "f-vertical-m-nudge": "10px",
  "f-vertical-m": "12px",
  "f-vertical-l": "16px",
  "f-vertical-xl": "20px",
  "f-vertical-xxl": "24px",
  "f-vertical-xxxl": "32px",
};

const fluentDuraton = {
  "f-ultra-fast": "50ms",
  "f-faster": "100ms",
  "f-fast": "150ms",
  "f-normal": "200ms",
  "f-gentle": "250ms",
  "f-slow": "300ms",
  "f-slower": "400ms",
  "f-ultra-slow": "500ms",
};

// const fluentCurve = {
//   "f-accelerate-max": "cubic-bezier(0.9,0.1,1,0.2)",
//   "f-accelerate-mid": "cubic-bezier(1,0,1,1)",
//   "f-accelerate-min": "cubic-bezier(0.8,0,0.78,1)",
//   "f-decelerate-max": "cubic-bezier(0.1,0.9,0.2,1)",
//   "f-decelerate-mid": "cubic-bezier(0,0,0,1)",
//   "f-decelerate-min": "cubic-bezier(0.33,0,0.1,1)",
//   "f-easy-ease-max": "cubic-bezier(0.8,0,0.2,1)",
//   "f-easy-ease": "cubic-bezier(0.33,0,0.67,1)",
//   "f-linear": "cubic-bezier(0,0,1,1)",
// };

const fluentColor = {
  "f-light-neutral-foreground1": "#ffffff",
  "f-light-neutral-foreground1-hover": "#ffffff",
  "f-light-neutral-foreground1-pressed": "#ffffff",
  "f-light-neutral-foreground1-selected": "#ffffff",
  "f-light-neutral-foreground2": "#d6d6d6",
  "f-light-neutral-foreground2-hover": "#ffffff",
  "f-light-neutral-foreground2-pressed": "#ffffff",
  "f-light-neutral-foreground2-selected": "#ffffff",
  "f-light-neutral-foreground2-brand-hover": "#259493",
  "f-light-neutral-foreground2-brand-pressed": "#258483",
  "f-light-neutral-foreground2-brand-selected": "#259493",
  "f-light-neutral-foreground3": "#adadad",
  "f-light-neutral-foreground3-hover": "#d6d6d6",
  "f-light-neutral-foreground3-pressed": "#d6d6d6",
  "f-light-neutral-foreground3-selected": "#d6d6d6",
  "f-light-neutral-foreground3-brand-hover": "#259493",
  "f-light-neutral-foreground3-brand-pressed": "#258483",
  "f-light-neutral-foreground3-brand-selected": "#259493",
  "f-light-neutral-foreground4": "#999999",
  "f-light-neutral-foreground-disabled": "#5c5c5c",
  "f-light-neutral-foreground-inverted-disabled": "rgba(255, 255, 255, 0.4)",
  "f-light-brand-foreground-link": "#259493",
  "f-light-brand-foreground-link-hover": "#25a4a3",
  "f-light-brand-foreground-link-pressed": "#258483",
  "f-light-brand-foreground-link-selected": "#259493",
  "f-light-neutral-foreground2-link": "#d6d6d6",
  "f-light-neutral-foreground2-link-hover": "#ffffff",
  "f-light-neutral-foreground2-link-pressed": "#ffffff",
  "f-light-neutral-foreground2-link-selected": "#ffffff",
  "f-light-compound-brand-foreground1": "#259493",
  "f-light-compound-brand-foreground1-hover": "#25a4a3",
  "f-light-compound-brand-foreground1-pressed": "#258483",
  "f-light-brand-foreground1": "#25a4a3",
  "f-light-brand-foreground2": "#23b4b3",
  "f-light-brand-foreground2-hover": "#21c4c4",
  "f-light-brand-foreground2-pressed": "#09f7f7",
  "f-light-neutral-foreground1-static": "#242424",
  "f-light-neutral-foreground-static-inverted": "#ffffff",
  "f-light-neutral-foreground-inverted": "#242424",
  "f-light-neutral-foreground-inverted-hover": "#242424",
  "f-light-neutral-foreground-inverted-pressed": "#242424",
  "f-light-neutral-foreground-inverted-selected": "#242424",
  "f-light-neutral-foreground-inverted2": "#242424",
  "f-light-neutral-foreground-on-brand": "#ffffff",
  "f-light-neutral-foreground-inverted-link": "#ffffff",
  "f-light-neutral-foreground-inverted-link-hover": "#ffffff",
  "f-light-neutral-foreground-inverted-link-pressed": "#ffffff",
  "f-light-neutral-foreground-inverted-link-selected": "#ffffff",
  "f-light-brand-foreground-inverted": "#247574",
  "f-light-brand-foreground-inverted-hover": "#226665",
  "f-light-brand-foreground-inverted-pressed": "#205756",
  "f-light-brand-foreground-on-light": "#247574",
  "f-light-brand-foreground-on-light-hover": "#226665",
  "f-light-brand-foreground-on-light-pressed": "#1d4948",
  "f-light-brand-foreground-on-light-selected": "#205756",
  "f-light-neutral-background1": "#292929",
  "f-light-neutral-background1-hover": "#3d3d3d",
  "f-light-neutral-background1-pressed": "#1f1f1f",
  "f-light-neutral-background1-selected": "#383838",
  "f-light-neutral-background2": "#1f1f1f",
  "f-light-neutral-background2-hover": "#333333",
  "f-light-neutral-background2-pressed": "#141414",
  "f-light-neutral-background2-selected": "#2e2e2e",
  "f-light-neutral-background3": "#141414",
  "f-light-neutral-background3-hover": "#292929",
  "f-light-neutral-background3-pressed": "#0a0a0a",
  "f-light-neutral-background3-selected": "#242424",
  "f-light-neutral-background4": "#0a0a0a",
  "f-light-neutral-background4-hover": "#1f1f1f",
  "f-light-neutral-background4-pressed": "#000000",
  "f-light-neutral-background4-selected": "#1a1a1a",
  "f-light-neutral-background5": "#000000",
  "f-light-neutral-background5-hover": "#141414",
  "f-light-neutral-background5-pressed": "#050505",
  "f-light-neutral-background5-selected": "#0f0f0f",
  "f-light-neutral-background6": "#333333",
  "f-light-neutral-background-inverted": "#ffffff",
  "f-light-neutral-background-static": "#3d3d3d",
  "f-light-neutral-background-alpha": "rgba(26, 26, 26, 0.5)",
  "f-light-neutral-background-alpha2": "rgba(31, 31, 31, 0.7)",
  "f-light-subtle-background": "transparent",
  "f-light-subtle-background-hover": "#383838",
  "f-light-subtle-background-pressed": "#2e2e2e",
  "f-light-subtle-background-selected": "#333333",
  "f-light-subtle-background-light-alpha-hover": "rgba(36, 36, 36, 0.8)",
  "f-light-subtle-background-light-alpha-pressed": "rgba(36, 36, 36, 0.5)",
  "f-light-subtle-background-light-alpha-selected": "transparent",
  "f-light-subtle-background-inverted": "transparent",
  "f-light-subtle-background-inverted-hover": "rgba(0, 0, 0, 0.1)",
  "f-light-subtle-background-inverted-pressed": "rgba(0, 0, 0, 0.3)",
  "f-light-subtle-background-inverted-selected": "rgba(0, 0, 0, 0.2)",
  "f-light-transparent-background": "transparent",
  "f-light-transparent-background-hover": "transparent",
  "f-light-transparent-background-pressed": "transparent",
  "f-light-transparent-background-selected": "transparent",
  "f-light-neutral-background-disabled": "#141414",
  "f-light-neutral-background-inverted-disabled": "rgba(255, 255, 255, 0.1)",
  "f-light-neutral-stencil1": "#575757",
  "f-light-neutral-stencil2": "#333333",
  "f-light-neutral-stencil1-alpha": "rgba(255, 255, 255, 0.1)",
  "f-light-neutral-stencil2-alpha": "rgba(255, 255, 255, 0.05)",
  "f-light-background-overlay": "rgba(0, 0, 0, 0.5)",
  "f-light-scrollbar-overlay": "rgba(255, 255, 255, 0.6)",
  "f-light-brand-background": "#226665",
  "f-light-brand-background-hover": "#247574",
  "f-light-brand-background-pressed": "#1a3b3a",
  "f-light-brand-background-selected": "#205756",
  "f-light-compound-brand-background": "#259493",
  "f-light-compound-brand-background-hover": "#25a4a3",
  "f-light-compound-brand-background-pressed": "#258483",
  "f-light-brand-background-static": "#247574",
  "f-light-brand-background2": "#111b1b",
  "f-light-brand-background2-hover": "#1a3b3a",
  "f-light-brand-background2-pressed": "#020404",
  "f-light-brand-background3-static": "#205756",
  "f-light-brand-background4-static": "#1a3b3a",
  "f-light-brand-background-inverted": "#ffffff",
  "f-light-brand-background-inverted-hover": "#09f7f7",
  "f-light-brand-background-inverted-pressed": "#1dd5d5",
  "f-light-brand-background-inverted-selected": "#16e6e6",
  "f-light-neutral-card-background": "#333333",
  "f-light-neutral-card-background-hover": "#3d3d3d",
  "f-light-neutral-card-background-pressed": "#2e2e2e",
  "f-light-neutral-card-background-selected": "#383838",
  "f-light-neutral-card-background-disabled": "#141414",
  "f-light-neutral-stroke-accessible": "#adadad",
  "f-light-neutral-stroke-accessible-hover": "#bdbdbd",
  "f-light-neutral-stroke-accessible-pressed": "#b3b3b3",
  "f-light-neutral-stroke-accessible-selected": "#259493",
  "f-light-neutral-stroke1": "#666666",
  "f-light-neutral-stroke1-hover": "#757575",
  "f-light-neutral-stroke1-pressed": "#6b6b6b",
  "f-light-neutral-stroke1-selected": "#707070",
  "f-light-neutral-stroke2": "#525252",
  "f-light-neutral-stroke3": "#3d3d3d",
  "f-light-neutral-stroke-subtle": "#0a0a0a",
  "f-light-neutral-stroke-on-brand": "#292929",
  "f-light-neutral-stroke-on-brand2": "#ffffff",
  "f-light-neutral-stroke-on-brand2-hover": "#ffffff",
  "f-light-neutral-stroke-on-brand2-pressed": "#ffffff",
  "f-light-neutral-stroke-on-brand2-selected": "#ffffff",
  "f-light-brand-stroke1": "#259493",
  "f-light-brand-stroke2": "#1d4948",
  "f-light-brand-stroke2-hover": "#1d4948",
  "f-light-brand-stroke2-pressed": "#172e2d",
  "f-light-brand-stroke2-contrast": "#1d4948",
  "f-light-compound-brand-stroke": "#259493",
  "f-light-compound-brand-stroke-hover": "#25a4a3",
  "f-light-compound-brand-stroke-pressed": "#258483",
  "f-light-neutral-stroke-disabled": "#424242",
  "f-light-neutral-stroke-inverted-disabled": "rgba(255, 255, 255, 0.4)",
  "f-light-transparent-stroke": "transparent",
  "f-light-transparent-stroke-interactive": "transparent",
  "f-light-transparent-stroke-disabled": "transparent",
  "f-light-neutral-stroke-alpha": "rgba(255, 255, 255, 0.1)",
  "f-light-neutral-stroke-alpha2": "rgba(255, 255, 255, 0.2)",
  "f-light-stroke-focus1": "#000000",
  "f-light-stroke-focus2": "#ffffff",

  "f-light-palette-red-background1": "#3f1011",
  "f-light-palette-red-background2": "#751d1f",
  "f-light-palette-red-background3": "#d13438",
  "f-light-palette-red-foreground1": "#e37d80",
  "f-light-palette-red-foreground2": "#f1bbbc",
  "f-light-palette-red-foreground3": "#e37d80",
  "f-light-palette-red-border-active": "#e37d80",
  "f-light-palette-red-border1": "#d13438",
  "f-light-palette-red-border2": "#e37d80",
  "f-light-palette-green-background1": "#052505",
  "f-light-palette-green-background2": "#094509",
  "f-light-palette-green-background3": "#107c10",
  "f-light-palette-green-foreground1": "#54b054",
  "f-light-palette-green-foreground2": "#9fd89f",
  "f-light-palette-green-foreground3": "#9fd89f",
  "f-light-palette-green-border-active": "#54b054",
  "f-light-palette-green-border1": "#107c10",
  "f-light-palette-green-border2": "#9fd89f",
  "f-light-palette-dark-orange-background1": "#411200",
  "f-light-palette-dark-orange-background2": "#7a2101",
  "f-light-palette-dark-orange-background3": "#da3b01",
  "f-light-palette-dark-orange-foreground1": "#e9835e",
  "f-light-palette-dark-orange-foreground2": "#f4bfab",
  "f-light-palette-dark-orange-foreground3": "#e9835e",
  "f-light-palette-dark-orange-border-active": "#e9835e",
  "f-light-palette-dark-orange-border1": "#da3b01",
  "f-light-palette-dark-orange-border2": "#e9835e",
  "f-light-palette-yellow-background1": "#4c4400",
  "f-light-palette-yellow-background2": "#817400",
  "f-light-palette-yellow-background3": "#fde300",
  "f-light-palette-yellow-foreground1": "#feee66",
  "f-light-palette-yellow-foreground2": "#fef7b2",
  "f-light-palette-yellow-foreground3": "#fdea3d",
  "f-light-palette-yellow-border-active": "#feee66",
  "f-light-palette-yellow-border1": "#fde300",
  "f-light-palette-yellow-border2": "#fdea3d",
  "f-light-palette-berry-background1": "#3a1136",
  "f-light-palette-berry-background2": "#6d2064",
  "f-light-palette-berry-background3": "#c239b3",
  "f-light-palette-berry-foreground1": "#da7ed0",
  "f-light-palette-berry-foreground2": "#edbbe7",
  "f-light-palette-berry-foreground3": "#d161c4",
  "f-light-palette-berry-border-active": "#da7ed0",
  "f-light-palette-berry-border1": "#c239b3",
  "f-light-palette-berry-border2": "#d161c4",
  "f-light-palette-light-green-background1": "#063004",
  "f-light-palette-light-green-background2": "#0b5a08",
  "f-light-palette-light-green-background3": "#13a10e",
  "f-light-palette-light-green-foreground1": "#5ec75a",
  "f-light-palette-light-green-foreground2": "#a7e3a5",
  "f-light-palette-light-green-foreground3": "#3db838",
  "f-light-palette-light-green-border-active": "#5ec75a",
  "f-light-palette-light-green-border1": "#13a10e",
  "f-light-palette-light-green-border2": "#3db838",
  "f-light-palette-marigold-background1": "#463100",
  "f-light-palette-marigold-background2": "#835b00",
  "f-light-palette-marigold-background3": "#eaa300",
  "f-light-palette-marigold-foreground1": "#f2c661",
  "f-light-palette-marigold-foreground2": "#f9e2ae",
  "f-light-palette-marigold-foreground3": "#efb839",
  "f-light-palette-marigold-border-active": "#f2c661",
  "f-light-palette-marigold-border1": "#eaa300",
  "f-light-palette-marigold-border2": "#efb839",
  "f-light-palette-red-foreground-inverted": "#d13438",
  "f-light-palette-green-foreground-inverted": "#107c10",
  "f-light-palette-yellow-foreground-inverted": "#817400",
  "f-light-palette-dark-red-background2": "#590815",
  "f-light-palette-dark-red-foreground2": "#d69ca5",
  "f-light-palette-dark-red-border-active": "#ac4f5e",
  "f-light-palette-cranberry-background2": "#6e0811",
  "f-light-palette-cranberry-foreground2": "#eeacb2",
  "f-light-palette-cranberry-border-active": "#dc626d",
  "f-light-palette-pumpkin-background2": "#712d09",
  "f-light-palette-pumpkin-foreground2": "#efc4ad",
  "f-light-palette-pumpkin-border-active": "#df8e64",
  "f-light-palette-peach-background2": "#8f4e00",
  "f-light-palette-peach-foreground2": "#ffddb3",
  "f-light-palette-peach-border-active": "#ffba66",
  "f-light-palette-gold-background2": "#6c5700",
  "f-light-palette-gold-foreground2": "#ecdfa5",
  "f-light-palette-gold-border-active": "#dac157",
  "f-light-palette-brass-background2": "#553e06",
  "f-light-palette-brass-foreground2": "#e0cea2",
  "f-light-palette-brass-border-active": "#c1a256",
  "f-light-palette-brown-background2": "#50301a",
  "f-light-palette-brown-foreground2": "#ddc3b0",
  "f-light-palette-brown-border-active": "#bb8f6f",
  "f-light-palette-forest-background2": "#294903",
  "f-light-palette-forest-foreground2": "#bdd99b",
  "f-light-palette-forest-border-active": "#85b44c",
  "f-light-palette-seafoam-background2": "#00723b",
  "f-light-palette-seafoam-foreground2": "#a8f0cd",
  "f-light-palette-seafoam-border-active": "#5ae0a0",
  "f-light-palette-dark-green-background2": "#063b06",
  "f-light-palette-dark-green-foreground2": "#9ad29a",
  "f-light-palette-dark-green-border-active": "#4da64d",
  "f-light-palette-light-teal-background2": "#00666d",
  "f-light-palette-light-teal-foreground2": "#a6e9ed",
  "f-light-palette-light-teal-border-active": "#58d3db",
  "f-light-palette-teal-background2": "#02494c",
  "f-light-palette-teal-foreground2": "#9bd9db",
  "f-light-palette-teal-border-active": "#4cb4b7",
  "f-light-palette-steel-background2": "#00333f",
  "f-light-palette-steel-foreground2": "#94c8d4",
  "f-light-palette-steel-border-active": "#4496a9",
  "f-light-palette-blue-background2": "#004377",
  "f-light-palette-blue-foreground2": "#a9d3f2",
  "f-light-palette-blue-border-active": "#5caae5",
  "f-light-palette-royal-blue-background2": "#002c4e",
  "f-light-palette-royal-blue-foreground2": "#9abfdc",
  "f-light-palette-royal-blue-border-active": "#4a89ba",
  "f-light-palette-cornflower-background2": "#2c3c85",
  "f-light-palette-cornflower-foreground2": "#c8d1fa",
  "f-light-palette-cornflower-border-active": "#93a4f4",
  "f-light-palette-navy-background2": "#001665",
  "f-light-palette-navy-foreground2": "#a3b2e8",
  "f-light-palette-navy-border-active": "#546fd2",
  "f-light-palette-lavender-background2": "#3f3682",
  "f-light-palette-lavender-foreground2": "#d2ccf8",
  "f-light-palette-lavender-border-active": "#a79cf1",
  "f-light-palette-purple-background2": "#341a51",
  "f-light-palette-purple-foreground2": "#c6b1de",
  "f-light-palette-purple-border-active": "#9470bd",
  "f-light-palette-grape-background2": "#4c0d55",
  "f-light-palette-grape-foreground2": "#d9a7e0",
  "f-light-palette-grape-border-active": "#b55fc1",
  "f-light-palette-lilac-background2": "#63276d",
  "f-light-palette-lilac-foreground2": "#e6bfed",
  "f-light-palette-lilac-border-active": "#cf87da",
  "f-light-palette-pink-background2": "#80215d",
  "f-light-palette-pink-foreground2": "#f7c0e3",
  "f-light-palette-pink-border-active": "#ef85c8",
  "f-light-palette-magenta-background2": "#6b0043",
  "f-light-palette-magenta-foreground2": "#eca5d1",
  "f-light-palette-magenta-border-active": "#d957a8",
  "f-light-palette-plum-background2": "#5a003b",
  "f-light-palette-plum-foreground2": "#d696c0",
  "f-light-palette-plum-border-active": "#ad4589",
  "f-light-palette-beige-background2": "#444241",
  "f-light-palette-beige-foreground2": "#d7d4d4",
  "f-light-palette-beige-border-active": "#afabaa",
  "f-light-palette-mink-background2": "#343231",
  "f-light-palette-mink-foreground2": "#cecccb",
  "f-light-palette-mink-border-active": "#9e9b99",
  "f-light-palette-platinum-background2": "#3b4447",
  "f-light-palette-platinum-foreground2": "#cdd6d8",
  "f-light-palette-platinum-border-active": "#a0adb2",
  "f-light-palette-anchor-background2": "#202427",
  "f-light-palette-anchor-foreground2": "#bcc3c7",
  "f-light-palette-anchor-border-active": "#808a90",
  "f-light-status-success-background1": "#052505",
  "f-light-status-success-background2": "#094509",
  "f-light-status-success-background3": "#107c10",
  "f-light-status-success-foreground1": "#54b054",
  "f-light-status-success-foreground2": "#9fd89f",
  "f-light-status-success-foreground3": "#9fd89f",
  "f-light-status-success-border-active": "#54b054",
  "f-light-status-success-foreground-inverted": "#0e700e",
  "f-light-status-success-border1": "#107c10",
  "f-light-status-success-border2": "#9fd89f",
  "f-light-status-warning-background1": "#4a1e04",
  "f-light-status-warning-background2": "#8a3707",
  "f-light-status-warning-background3": "#f7630c",
  "f-light-status-warning-foreground1": "#faa06b",
  "f-light-status-warning-foreground2": "#fdcfb4",
  "f-light-status-warning-foreground3": "#f98845",
  "f-light-status-warning-border-active": "#faa06b",
  "f-light-status-warning-foreground-inverted": "#bc4b09",
  "f-light-status-warning-border1": "#f7630c",
  "f-light-status-warning-border2": "#f98845",
  "f-light-status-danger-background1": "#3b0509",
  "f-light-status-danger-background2": "#6e0811",
  "f-light-status-danger-background3": "#c50f1f",
  "f-light-status-danger-foreground1": "#dc626d",
  "f-light-status-danger-foreground2": "#eeacb2",
  "f-light-status-danger-foreground3": "#eeacb2",
  "f-light-status-danger-border-active": "#dc626d",
  "f-light-status-danger-foreground-inverted": "#b10e1c",
  "f-light-status-danger-border1": "#c50f1f",
  "f-light-status-danger-border2": "#dc626d",
  "f-light-status-danger-background3-hover": "#b10e1c",
  "f-light-status-danger-background3-pressed": "#960b18",

  "f-dark-neutral-foreground1": "#242424",
  "f-dark-neutral-foreground1-hover": "#242424",
  "f-dark-neutral-foreground1-pressed": "#242424",
  "f-dark-neutral-foreground1-selected": "#242424",
  "f-dark-neutral-foreground2": "#424242",
  "f-dark-neutral-foreground2-hover": "#242424",
  "f-dark-neutral-foreground2-pressed": "#242424",
  "f-dark-neutral-foreground2-selected": "#242424",
  "f-dark-neutral-foreground2-brand-hover": "#247574",
  "f-dark-neutral-foreground2-brand-pressed": "#226665",
  "f-dark-neutral-foreground2-brand-selected": "#247574",
  "f-dark-neutral-foreground3": "#616161",
  "f-dark-neutral-foreground3-hover": "#424242",
  "f-dark-neutral-foreground3-pressed": "#424242",
  "f-dark-neutral-foreground3-selected": "#424242",
  "f-dark-neutral-foreground3-brand-hover": "#247574",
  "f-dark-neutral-foreground3-brand-pressed": "#226665",
  "f-dark-neutral-foreground3-brand-selected": "#247574",
  "f-dark-neutral-foreground4": "#707070",
  "f-dark-neutral-foreground-disabled": "#bdbdbd",
  "f-dark-neutral-foreground-inverted-disabled": "rgba(255, 255, 255, 0.4)",
  "f-dark-brand-foreground-link": "#226665",
  "f-dark-brand-foreground-link-hover": "#205756",
  "f-dark-brand-foreground-link-pressed": "#1a3b3a",
  "f-dark-brand-foreground-link-selected": "#226665",
  "f-dark-neutral-foreground2-link": "#424242",
  "f-dark-neutral-foreground2-link-hover": "#242424",
  "f-dark-neutral-foreground2-link-pressed": "#242424",
  "f-dark-neutral-foreground2-link-selected": "#242424",
  "f-dark-compound-brand-foreground1": "#247574",
  "f-dark-compound-brand-foreground1-hover": "#226665",
  "f-dark-compound-brand-foreground1-pressed": "#205756",
  "f-dark-brand-foreground1": "#247574",
  "f-dark-brand-foreground2": "#226665",
  "f-dark-brand-foreground2-hover": "#205756",
  "f-dark-brand-foreground2-pressed": "#172e2d",
  "f-dark-neutral-foreground1-static": "#242424",
  "f-dark-neutral-foreground-static-inverted": "#ffffff",
  "f-dark-neutral-foreground-inverted": "#ffffff",
  "f-dark-neutral-foreground-inverted-hover": "#ffffff",
  "f-dark-neutral-foreground-inverted-pressed": "#ffffff",
  "f-dark-neutral-foreground-inverted-selected": "#ffffff",
  "f-dark-neutral-foreground-inverted2": "#ffffff",
  "f-dark-neutral-foreground-on-brand": "#ffffff",
  "f-dark-neutral-foreground-inverted-link": "#ffffff",
  "f-dark-neutral-foreground-inverted-link-hover": "#ffffff",
  "f-dark-neutral-foreground-inverted-link-pressed": "#ffffff",
  "f-dark-neutral-foreground-inverted-link-selected": "#ffffff",
  "f-dark-brand-foreground-inverted": "#259493",
  "f-dark-brand-foreground-inverted-hover": "#25a4a3",
  "f-dark-brand-foreground-inverted-pressed": "#259493",
  "f-dark-brand-foreground-on-light": "#247574",
  "f-dark-brand-foreground-on-light-hover": "#226665",
  "f-dark-brand-foreground-on-light-pressed": "#1d4948",
  "f-dark-brand-foreground-on-light-selected": "#205756",
  "f-dark-neutral-background1": "#ffffff",
  "f-dark-neutral-background1-hover": "#f5f5f5",
  "f-dark-neutral-background1-pressed": "#e0e0e0",
  "f-dark-neutral-background1-selected": "#ebebeb",
  "f-dark-neutral-background2": "#fafafa",
  "f-dark-neutral-background2-hover": "#f0f0f0",
  "f-dark-neutral-background2-pressed": "#dbdbdb",
  "f-dark-neutral-background2-selected": "#e6e6e6",
  "f-dark-neutral-background3": "#f5f5f5",
  "f-dark-neutral-background3-hover": "#ebebeb",
  "f-dark-neutral-background3-pressed": "#d6d6d6",
  "f-dark-neutral-background3-selected": "#e0e0e0",
  "f-dark-neutral-background4": "#f0f0f0",
  "f-dark-neutral-background4-hover": "#fafafa",
  "f-dark-neutral-background4-pressed": "#f5f5f5",
  "f-dark-neutral-background4-selected": "#ffffff",
  "f-dark-neutral-background5": "#ebebeb",
  "f-dark-neutral-background5-hover": "#f5f5f5",
  "f-dark-neutral-background5-pressed": "#f0f0f0",
  "f-dark-neutral-background5-selected": "#fafafa",
  "f-dark-neutral-background6": "#e6e6e6",
  "f-dark-neutral-background-inverted": "#292929",
  "f-dark-neutral-background-static": "#333333",
  "f-dark-neutral-background-alpha": "rgba(255, 255, 255, 0.5)",
  "f-dark-neutral-background-alpha2": "rgba(255, 255, 255, 0.8)",
  "f-dark-subtle-background": "transparent",
  "f-dark-subtle-background-hover": "#f5f5f5",
  "f-dark-subtle-background-pressed": "#e0e0e0",
  "f-dark-subtle-background-selected": "#ebebeb",
  "f-dark-subtle-background-light-alpha-hover": "rgba(255, 255, 255, 0.7)",
  "f-dark-subtle-background-light-alpha-pressed": "rgba(255, 255, 255, 0.5)",
  "f-dark-subtle-background-light-alpha-selected": "transparent",
  "f-dark-subtle-background-inverted": "transparent",
  "f-dark-subtle-background-inverted-hover": "rgba(0, 0, 0, 0.1)",
  "f-dark-subtle-background-inverted-pressed": "rgba(0, 0, 0, 0.3)",
  "f-dark-subtle-background-inverted-selected": "rgba(0, 0, 0, 0.2)",
  "f-dark-transparent-background": "transparent",
  "f-dark-transparent-background-hover": "transparent",
  "f-dark-transparent-background-pressed": "transparent",
  "f-dark-transparent-background-selected": "transparent",
  "f-dark-neutral-background-disabled": "#f0f0f0",
  "f-dark-neutral-background-inverted-disabled": "rgba(255, 255, 255, 0.1)",
  "f-dark-neutral-stencil1": "#e6e6e6",
  "f-dark-neutral-stencil2": "#fafafa",
  "f-dark-neutral-stencil1-alpha": "rgba(0, 0, 0, 0.1)",
  "f-dark-neutral-stencil2-alpha": "rgba(0, 0, 0, 0.05)",
  "f-dark-background-overlay": "rgba(0, 0, 0, 0.4)",
  "f-dark-scrollbar-overlay": "rgba(0, 0, 0, 0.5)",
  "f-dark-brand-background": "#247574",
  "f-dark-brand-background-hover": "#226665",
  "f-dark-brand-background-pressed": "#1a3b3a",
  "f-dark-brand-background-selected": "#205756",
  "f-dark-compound-brand-background": "#247574",
  "f-dark-compound-brand-background-hover": "#226665",
  "f-dark-compound-brand-background-pressed": "#205756",
  "f-dark-brand-background-static": "#247574",
  "f-dark-brand-background2": "#09f7f7",
  "f-dark-brand-background2-hover": "#16e6e6",
  "f-dark-brand-background2-pressed": "#21c4c4",
  "f-dark-brand-background3-static": "#205756",
  "f-dark-brand-background4-static": "#1a3b3a",
  "f-dark-brand-background-inverted": "#ffffff",
  "f-dark-brand-background-inverted-hover": "#09f7f7",
  "f-dark-brand-background-inverted-pressed": "#1dd5d5",
  "f-dark-brand-background-inverted-selected": "#16e6e6",
  "f-dark-neutral-card-background": "#fafafa",
  "f-dark-neutral-card-background-hover": "#ffffff",
  "f-dark-neutral-card-background-pressed": "#f5f5f5",
  "f-dark-neutral-card-background-selected": "#ebebeb",
  "f-dark-neutral-card-background-disabled": "#f0f0f0",
  "f-dark-neutral-stroke-accessible": "#616161",
  "f-dark-neutral-stroke-accessible-hover": "#575757",
  "f-dark-neutral-stroke-accessible-pressed": "#4d4d4d",
  "f-dark-neutral-stroke-accessible-selected": "#247574",
  "f-dark-neutral-stroke1": "#d1d1d1",
  "f-dark-neutral-stroke1-hover": "#c7c7c7",
  "f-dark-neutral-stroke1-pressed": "#b3b3b3",
  "f-dark-neutral-stroke1-selected": "#bdbdbd",
  "f-dark-neutral-stroke2": "#e0e0e0",
  "f-dark-neutral-stroke3": "#f0f0f0",
  "f-dark-neutral-stroke-subtle": "#e0e0e0",
  "f-dark-neutral-stroke-on-brand": "#ffffff",
  "f-dark-neutral-stroke-on-brand2": "#ffffff",
  "f-dark-neutral-stroke-on-brand2-hover": "#ffffff",
  "f-dark-neutral-stroke-on-brand2-pressed": "#ffffff",
  "f-dark-neutral-stroke-on-brand2-selected": "#ffffff",
  "f-dark-brand-stroke1": "#247574",
  "f-dark-brand-stroke2": "#1dd5d5",
  "f-dark-brand-stroke2-hover": "#23b4b3",
  "f-dark-brand-stroke2-pressed": "#247574",
  "f-dark-brand-stroke2-contrast": "#1dd5d5",
  "f-dark-compound-brand-stroke": "#247574",
  "f-dark-compound-brand-stroke-hover": "#226665",
  "f-dark-compound-brand-stroke-pressed": "#205756",
  "f-dark-neutral-stroke-disabled": "#e0e0e0",
  "f-dark-neutral-stroke-inverted-disabled": "rgba(255, 255, 255, 0.4)",
  "f-dark-transparent-stroke": "transparent",
  "f-dark-transparent-stroke-interactive": "transparent",
  "f-dark-transparent-stroke-disabled": "transparent",
  "f-dark-neutral-stroke-alpha": "rgba(0, 0, 0, 0.05)",
  "f-dark-neutral-stroke-alpha2": "rgba(255, 255, 255, 0.2)",
  "f-dark-stroke-focus1": "#ffffff",
  "f-dark-stroke-focus2": "#000000",
  "f-dark-palette-red-background1": "#fdf6f6",
  "f-dark-palette-red-background2": "#f1bbbc",
  "f-dark-palette-red-background3": "#d13438",
  "f-dark-palette-red-foreground1": "#bc2f32",
  "f-dark-palette-red-foreground2": "#751d1f",
  "f-dark-palette-red-foreground3": "#d13438",
  "f-dark-palette-red-border-active": "#d13438",
  "f-dark-palette-red-border1": "#f1bbbc",
  "f-dark-palette-red-border2": "#d13438",
  "f-dark-palette-green-background1": "#f1faf1",
  "f-dark-palette-green-background2": "#9fd89f",
  "f-dark-palette-green-background3": "#107c10",
  "f-dark-palette-green-foreground1": "#0e700e",
  "f-dark-palette-green-foreground2": "#094509",
  "f-dark-palette-green-foreground3": "#107c10",
  "f-dark-palette-green-border-active": "#107c10",
  "f-dark-palette-green-border1": "#9fd89f",
  "f-dark-palette-green-border2": "#107c10",
  "f-dark-palette-dark-orange-background1": "#fdf6f3",
  "f-dark-palette-dark-orange-background2": "#f4bfab",
  "f-dark-palette-dark-orange-background3": "#da3b01",
  "f-dark-palette-dark-orange-foreground1": "#c43501",
  "f-dark-palette-dark-orange-foreground2": "#7a2101",
  "f-dark-palette-dark-orange-foreground3": "#da3b01",
  "f-dark-palette-dark-orange-border-active": "#da3b01",
  "f-dark-palette-dark-orange-border1": "#f4bfab",
  "f-dark-palette-dark-orange-border2": "#da3b01",
  "f-dark-palette-yellow-background1": "#fffef5",
  "f-dark-palette-yellow-background2": "#fef7b2",
  "f-dark-palette-yellow-background3": "#fde300",
  "f-dark-palette-yellow-foreground1": "#817400",
  "f-dark-palette-yellow-foreground2": "#817400",
  "f-dark-palette-yellow-foreground3": "#fde300",
  "f-dark-palette-yellow-border-active": "#fde300",
  "f-dark-palette-yellow-border1": "#fef7b2",
  "f-dark-palette-yellow-border2": "#fde300",
  "f-dark-palette-berry-background1": "#fdf5fc",
  "f-dark-palette-berry-background2": "#edbbe7",
  "f-dark-palette-berry-background3": "#c239b3",
  "f-dark-palette-berry-foreground1": "#af33a1",
  "f-dark-palette-berry-foreground2": "#6d2064",
  "f-dark-palette-berry-foreground3": "#c239b3",
  "f-dark-palette-berry-border-active": "#c239b3",
  "f-dark-palette-berry-border1": "#edbbe7",
  "f-dark-palette-berry-border2": "#c239b3",
  "f-dark-palette-light-green-background1": "#f2fbf2",
  "f-dark-palette-light-green-background2": "#a7e3a5",
  "f-dark-palette-light-green-background3": "#13a10e",
  "f-dark-palette-light-green-foreground1": "#11910d",
  "f-dark-palette-light-green-foreground2": "#0b5a08",
  "f-dark-palette-light-green-foreground3": "#13a10e",
  "f-dark-palette-light-green-border-active": "#13a10e",
  "f-dark-palette-light-green-border1": "#a7e3a5",
  "f-dark-palette-light-green-border2": "#13a10e",
  "f-dark-palette-marigold-background1": "#fefbf4",
  "f-dark-palette-marigold-background2": "#f9e2ae",
  "f-dark-palette-marigold-background3": "#eaa300",
  "f-dark-palette-marigold-foreground1": "#d39300",
  "f-dark-palette-marigold-foreground2": "#835b00",
  "f-dark-palette-marigold-foreground3": "#eaa300",
  "f-dark-palette-marigold-border-active": "#eaa300",
  "f-dark-palette-marigold-border1": "#f9e2ae",
  "f-dark-palette-marigold-border2": "#eaa300",
  "f-dark-palette-red-foreground-inverted": "#dc5e62",
  "f-dark-palette-green-foreground-inverted": "#359b35",
  "f-dark-palette-yellow-foreground-inverted": "#fef7b2",
  "f-dark-palette-dark-red-background2": "#d69ca5",
  "f-dark-palette-dark-red-foreground2": "#420610",
  "f-dark-palette-dark-red-border-active": "#750b1c",
  "f-dark-palette-cranberry-background2": "#eeacb2",
  "f-dark-palette-cranberry-foreground2": "#6e0811",
  "f-dark-palette-cranberry-border-active": "#c50f1f",
  "f-dark-palette-pumpkin-background2": "#efc4ad",
  "f-dark-palette-pumpkin-foreground2": "#712d09",
  "f-dark-palette-pumpkin-border-active": "#ca5010",
  "f-dark-palette-peach-background2": "#ffddb3",
  "f-dark-palette-peach-foreground2": "#8f4e00",
  "f-dark-palette-peach-border-active": "#ff8c00",
  "f-dark-palette-gold-background2": "#ecdfa5",
  "f-dark-palette-gold-foreground2": "#6c5700",
  "f-dark-palette-gold-border-active": "#c19c00",
  "f-dark-palette-brass-background2": "#e0cea2",
  "f-dark-palette-brass-foreground2": "#553e06",
  "f-dark-palette-brass-border-active": "#986f0b",
  "f-dark-palette-brown-background2": "#ddc3b0",
  "f-dark-palette-brown-foreground2": "#50301a",
  "f-dark-palette-brown-border-active": "#8e562e",
  "f-dark-palette-forest-background2": "#bdd99b",
  "f-dark-palette-forest-foreground2": "#294903",
  "f-dark-palette-forest-border-active": "#498205",
  "f-dark-palette-seafoam-background2": "#a8f0cd",
  "f-dark-palette-seafoam-foreground2": "#00723b",
  "f-dark-palette-seafoam-border-active": "#00cc6a",
  "f-dark-palette-dark-green-background2": "#9ad29a",
  "f-dark-palette-dark-green-foreground2": "#063b06",
  "f-dark-palette-dark-green-border-active": "#0b6a0b",
  "f-dark-palette-light-teal-background2": "#a6e9ed",
  "f-dark-palette-light-teal-foreground2": "#00666d",
  "f-dark-palette-light-teal-border-active": "#00b7c3",
  "f-dark-palette-teal-background2": "#9bd9db",
  "f-dark-palette-teal-foreground2": "#02494c",
  "f-dark-palette-teal-border-active": "#038387",
  "f-dark-palette-steel-background2": "#94c8d4",
  "f-dark-palette-steel-foreground2": "#00333f",
  "f-dark-palette-steel-border-active": "#005b70",
  "f-dark-palette-blue-background2": "#a9d3f2",
  "f-dark-palette-blue-foreground2": "#004377",
  "f-dark-palette-blue-border-active": "#0078d4",
  "f-dark-palette-royal-blue-background2": "#9abfdc",
  "f-dark-palette-royal-blue-foreground2": "#002c4e",
  "f-dark-palette-royal-blue-border-active": "#004e8c",
  "f-dark-palette-cornflower-background2": "#c8d1fa",
  "f-dark-palette-cornflower-foreground2": "#2c3c85",
  "f-dark-palette-cornflower-border-active": "#4f6bed",
  "f-dark-palette-navy-background2": "#a3b2e8",
  "f-dark-palette-navy-foreground2": "#001665",
  "f-dark-palette-navy-border-active": "#0027b4",
  "f-dark-palette-lavender-background2": "#d2ccf8",
  "f-dark-palette-lavender-foreground2": "#3f3682",
  "f-dark-palette-lavender-border-active": "#7160e8",
  "f-dark-palette-purple-background2": "#c6b1de",
  "f-dark-palette-purple-foreground2": "#341a51",
  "f-dark-palette-purple-border-active": "#5c2e91",
  "f-dark-palette-grape-background2": "#d9a7e0",
  "f-dark-palette-grape-foreground2": "#4c0d55",
  "f-dark-palette-grape-border-active": "#881798",
  "f-dark-palette-lilac-background2": "#e6bfed",
  "f-dark-palette-lilac-foreground2": "#63276d",
  "f-dark-palette-lilac-border-active": "#b146c2",
  "f-dark-palette-pink-background2": "#f7c0e3",
  "f-dark-palette-pink-foreground2": "#80215d",
  "f-dark-palette-pink-border-active": "#e43ba6",
  "f-dark-palette-magenta-background2": "#eca5d1",
  "f-dark-palette-magenta-foreground2": "#6b0043",
  "f-dark-palette-magenta-border-active": "#bf0077",
  "f-dark-palette-plum-background2": "#d696c0",
  "f-dark-palette-plum-foreground2": "#43002b",
  "f-dark-palette-plum-border-active": "#77004d",
  "f-dark-palette-beige-background2": "#d7d4d4",
  "f-dark-palette-beige-foreground2": "#444241",
  "f-dark-palette-beige-border-active": "#7a7574",
  "f-dark-palette-mink-background2": "#cecccb",
  "f-dark-palette-mink-foreground2": "#343231",
  "f-dark-palette-mink-border-active": "#5d5a58",
  "f-dark-palette-platinum-background2": "#cdd6d8",
  "f-dark-palette-platinum-foreground2": "#3b4447",
  "f-dark-palette-platinum-border-active": "#69797e",
  "f-dark-palette-anchor-background2": "#bcc3c7",
  "f-dark-palette-anchor-foreground2": "#202427",
  "f-dark-palette-anchor-border-active": "#394146",
  "f-dark-status-success-background1": "#f1faf1",
  "f-dark-status-success-background2": "#9fd89f",
  "f-dark-status-success-background3": "#107c10",
  "f-dark-status-success-foreground1": "#0e700e",
  "f-dark-status-success-foreground2": "#094509",
  "f-dark-status-success-foreground3": "#107c10",
  "f-dark-status-success-foreground-inverted": "#54b054",
  "f-dark-status-success-border-active": "#107c10",
  "f-dark-status-success-border1": "#9fd89f",
  "f-dark-status-success-border2": "#107c10",
  "f-dark-status-warning-background1": "#fff9f5",
  "f-dark-status-warning-background2": "#fdcfb4",
  "f-dark-status-warning-background3": "#f7630c",
  "f-dark-status-warning-foreground1": "#bc4b09",
  "f-dark-status-warning-foreground2": "#8a3707",
  "f-dark-status-warning-foreground3": "#bc4b09",
  "f-dark-status-warning-foreground-inverted": "#faa06b",
  "f-dark-status-warning-border-active": "#f7630c",
  "f-dark-status-warning-border1": "#fdcfb4",
  "f-dark-status-warning-border2": "#bc4b09",
  "f-dark-status-danger-background1": "#fdf3f4",
  "f-dark-status-danger-background2": "#eeacb2",
  "f-dark-status-danger-background3": "#c50f1f",
  "f-dark-status-danger-foreground1": "#b10e1c",
  "f-dark-status-danger-foreground2": "#6e0811",
  "f-dark-status-danger-foreground3": "#c50f1f",
  "f-dark-status-danger-foreground-inverted": "#dc626d",
  "f-dark-status-danger-border-active": "#c50f1f",
  "f-dark-status-danger-border1": "#eeacb2",
  "f-dark-status-danger-border2": "#c50f1f",
  "f-dark-status-danger-background3-hover": "#b10e1c",
  "f-dark-status-danger-background3-pressed": "#960b18",
};

const fluentShadow = {
  "f-light-shadow2": "0 0 2px rgba(0,0,0,0.24), 0 1px 2px rgba(0,0,0,0.28)",
  "f-light-shadow4": "0 0 2px rgba(0,0,0,0.24), 0 2px 4px rgba(0,0,0,0.28)",
  "f-light-shadow8": "0 0 2px rgba(0,0,0,0.24), 0 4px 8px rgba(0,0,0,0.28)",
  "f-light-shadow16": "0 0 2px rgba(0,0,0,0.24), 0 8px 16px rgba(0,0,0,0.28)",
  "f-light-shadow28": "0 0 8px rgba(0,0,0,0.24), 0 14px 28px rgba(0,0,0,0.28)",
  "f-light-shadow64": "0 0 8px rgba(0,0,0,0.24), 0 32px 64px rgba(0,0,0,0.28)",
  "f-dark-shadow2": "0 0 2px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.14)",
  "f-dark-shadow4": "0 0 2px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.14)",
  "f-dark-shadow8": "0 0 2px rgba(0,0,0,0.12), 0 4px 8px rgba(0,0,0,0.14)",
  "f-dark-shadow16": "0 0 2px rgba(0,0,0,0.12), 0 8px 16px rgba(0,0,0,0.14)",
  "f-dark-shadow28": "0 0 8px rgba(0,0,0,0.12), 0 14px 28px rgba(0,0,0,0.14)",
  "f-dark-shadow64": "0 0 8px rgba(0,0,0,0.12), 0 32px 64px rgba(0,0,0,0.14)",
  "f-shadow2-brand": "0 0 2px rgba(0,0,0,0.30), 0 1px 2px rgba(0,0,0,0.25)",
  "f-shadow4-brand": "0 0 2px rgba(0,0,0,0.30), 0 2px 4px rgba(0,0,0,0.25)",
  "f-shadow8-brand": "0 0 2px rgba(0,0,0,0.30), 0 4px 8px rgba(0,0,0,0.25)",
  "f-shadow16-brand": "0 0 2px rgba(0,0,0,0.30), 0 8px 16px rgba(0,0,0,0.25)",
  "f-shadow28-brand": "0 0 8px rgba(0,0,0,0.30), 0 14px 28px rgba(0,0,0,0.25)",
  "f-shadow64-brand": "0 0 8px rgba(0,0,0,0.30), 0 32px 64px rgba(0,0,0,0.25)"
}

const fluentShadowColor = {
  "f-light-neutral-shadow-ambient": "rgba(0,0,0,0.24)",
  "f-light-neutral-shadow-key": "rgba(0,0,0,0.28)",
  "f-light-neutral-shadow-ambient-lighter": "rgba(0,0,0,0.12)",
  "f-light-neutral-shadow-key-lighter": "rgba(0,0,0,0.14)",
  "f-light-neutral-shadow-ambient-darker": "rgba(0,0,0,0.40)",
  "f-light-neutral-shadow-key-darker": "rgba(0,0,0,0.48)",
  "f-light-brand-shadow-ambient": "rgba(0,0,0,0.30)",
  "f-light-brand-shadow-key": "rgba(0,0,0,0.25)",
  "f-dark-neutral-shadow-ambient": "rgba(0,0,0,0.12)",
  "f-dark-neutral-shadow-key": "rgba(0,0,0,0.14)",
  "f-dark-neutral-shadow-ambient-lighter": "rgba(0,0,0,0.06)",
  "f-dark-neutral-shadow-key-lighter": "rgba(0,0,0,0.07)",
  "f-dark-neutral-shadow-ambient-darker": "rgba(0,0,0,0.20)",
  "f-dark-neutral-shadow-key-darker": "rgba(0,0,0,0.24)",
  "f-dark-brand-shadow-ambient": "rgba(0,0,0,0.30)",
  "f-dark-brand-shadow-key": "rgba(0,0,0,0.25)",
}

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      borderRadius: {
        ...fluentBorderRadius,
      },
      transitionDuration: {
        ...fluentDuraton,
      },
      spacing: { ...fluentSpacing },
      fontSize: { ...fluentFontSize },
      lineHeight: { ...fluentLineHight },
      gridTemplateColumns: {
        "auto-300": "repeat(auto-fill, minmax(300px, 1fr))",
      },
      boxShadow: {
        ...fluentShadow
      },
      boxShadowColor: { ...fluentShadowColor },
      colors: {
        ...fluentColor, ...fluentShadowColor
      },
      fontFamily: { ...fluentFontFamily },
      fontWeight: { ...fluentFontWeight },
      strokeWidth: { ...fluentStrokeWidth },
      keyframes: {
        "3-5-1-y16": {
          "0%, 28%": { transform: "translateY(0)" },
          "33%, 61%": { transform: "translateY(-2rem)" },
          "67%, 94%": { transform: "translateY(-4rem)" },
          "100%": { transform: "translateY(0)" },
        },
      },
      animation: {
        "index-cw-tip": "3-5-1-y16 7.2s linear infinite",
      },
    },
  },
  plugins: [],
};
